name: Build JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build plugin
        run: |
          mkdir target
          javac -d target $(find ./src -name "*.java")
          cp plugin.yml target/
      - name: Package JAR
        run: |
          cd target
          jar cf RPGSkillPlugin-1.20.1.jar *
      - uses: actions/upload-artifact@v4
        with:
          name: RPGSkillPlugin-1.20.1
          path: target/RPGSkillPlugin-1.20.1.jar
